import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { AuthProvider } from './context/authContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Theme>
            <nav>
              <h1>Jayapan</h1>
            </nav>
            <section className="flex min-h-screen justify-center items-center">
              {children}
            </section>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
