import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { AuthProvider } from './context/authContext';
import Sidebar from './components/sidebar/Sidebar';
import Navbar from './components/layout/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {



  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Theme accentColor="teal" grayColor="sand" radius="full">
            <Navbar />
            <main className='flex gap-2'>
              <section className='p-4 w-[200px] bg-emerald-600 text-white flex flex-col gap-2'>
                <Sidebar />
              </section>
              <section className=" min-h-screen justify-center items-center">
                {children}
              </section>
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
